#!/usr/bin/env bash
#This is a while loop and IFS
while IFS=: read -r user _ uid gid _ home shell; do
  info="$user"
  echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd
