#!/usr/bin/env bash
# Script to stop the 4-to_infinity_and_beyond process

# Find the PID(s) of the process using pgrep
pid=$(pgrep -f 4-to_infinity_and_beyond)

# If PID exists, kill the process
if [ -n "$pid" ]; then
    kill "$pid"
fi
