#!/usr/bin/env bash
# 8-beheaded_process: kills the 7-highlander process

# Find the PID(s) of the 7-highlander process
pid=$(pgrep -f 7-highlander)

# If PID exists, terminate the process
if [ -n "$pid" ]; then
    kill -9 "$pid"
fi
